version: '2'
services:
  myhero-app:
    build: .
    image: juliocisco/myhero-app
    ports:
     - "15001:5000"
    environment:
     - myhero_data_key=${MYHERO_DATA_KEY}
     - myhero_app_key=${MYHERO_APP_KEY}
     - myhero_data_server=http://myhero-data:5000
networks:
  default:
     external:
       name: myherodata_default
